export const USER_POST_REQUEST = "USER_POST_REQUEST";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_FAILURE = "USER_POST_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOAD_POSTER_REQUEST = "LOAD_POSTER_REQUEST ";
export const LOAD_POSTER_SUCCESS = "LOAD_POSTER_SUCCESS";
export const LOAD_POSTER_FAILURE = "LOAD_POSTER_FAILURE";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const LOAD_REGISTRANT_REQUEST = "LOAD_REGISTRANT_REQUEST";
export const LOAD_REGISTRANT_SUCCESS = "LOAD_REGISTRANT_SUCCESS";
export const LOAD_REGISTRANT_FAILURE = "LOAD_REGISTRANT_FAILURE ";
